// Generate src/lib/cutsceneMapBorders.js — host province/state internal border
// lines for the pregame Cutscene's vintage paper map (Part 2 overhaul), baked
// as SVG path strings in the SAME 1000×600 chart projection as cutsceneMap.js's
// GEO coastlines, so they line up with zero runtime cost or extra JSON in the
// Simulator bundle (matching cutsceneMap.js's own stated intent).
//
// SOURCE: src/data/hostSubdivisions.json (Natural Earth admin-1, already
// Douglas-Peucker simplified - see generate_host_subdivisions.mjs). Alaska and
// Hawaii are dropped: the chart window is a continental North America crop
// (LNG0 -140), so their real coordinates would draw stray marks off-frame.
//
// Run: node scripts/generate_cutscene_borders.mjs

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import hostSubdivisions from '../src/data/hostSubdivisions.json' with { type: 'json' }

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../src/lib/cutsceneMapBorders.js')

const W = 1000, H = 600, PADX = 90, PADY = 60
const LNG0 = -140, LNG1 = -52, LAT0 = 12, LAT1 = 74
const project = (lng, lat) => {
  const x = PADX + ((lng - LNG0) / (LNG1 - LNG0)) * (W - 2 * PADX)
  const y = PADY + ((LAT1 - lat) / (LAT1 - LAT0)) * (H - 2 * PADY)
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10]
}

const EXCLUDE = { US: new Set(['Alaska', 'Hawaii']) }

function bordersFor(code) {
  const ex = EXCLUDE[code]
  const subs = (hostSubdivisions[code]?.subs || []).filter((s) => !ex?.has(s.name))
  let d = ''
  for (const s of subs) {
    for (const ring of s.rings) {
      const pts = ring.map(([lng, lat]) => project(lng, lat))
      d += `M${pts.map((p) => p.join(',')).join('L')} `
    }
  }
  return d.trim()
}

const out = {
  canada: bordersFor('CA'),
  usa: bordersFor('US'),
  mexico: bordersFor('MX'),
}

const body = `// Generated by scripts/generate_cutscene_borders.mjs - do not hand-edit.
// Host province/state internal borders for the pregame Cutscene's vintage
// paper map, pre-projected into the same 1000×600 chart space as
// cutsceneMap.js's GEO coastlines (Part 2 overhaul).
export const GEO_BORDERS = ${JSON.stringify(out, null, 2)}
`
writeFileSync(OUT, body)
console.log(`wrote ${OUT} (${(body.length / 1024).toFixed(1)} KB)`)
